# Generated by Django 5.2.8 on 2025-11-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ทะเบียนที่')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='วันที่ลงทะเบียน')),
                ('filed_date', models.DateField(blank=True, null=True, verbose_name='วันที่เก็บเข้าแฟ้ม')),
                ('related_doc_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='เลขที่เอกสารที่เกี่ยวข้อง')),
                ('withdrawal_set_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='เลขที่ชุดเบิก')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ทะเบียนเอกสาร',
                'verbose_name_plural': 'ทะเบียนเอกสาร',
                'ordering': ['-reg_date', 'reg_no'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ/ชื่อเอกสาร')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('content', models.TextField(blank=True, verbose_name='เนื้อหา/คำอธิบาย')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='ไฟล์แนบ')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kurupun.documentregister')),
            ],
            options={
                'verbose_name': 'รายการเอกสาร',
                'verbose_name_plural': 'รายการเอกสาร',
                'ordering': ['order', 'id'],
            },
        ),
    ]
