# Generated by Django 5.2.8 on 2025-11-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=100, verbose_name='รหัสคลังสินค้า')),
                ('type_id', models.CharField(max_length=100, verbose_name='รหัสประเภทพัสดุ')),
                ('des_id', models.CharField(max_length=100, verbose_name='รหัสรายละเอียดพัสดุ')),
                ('des_name', models.TextField(verbose_name='ชื่อรายละเอียดพัสดุ')),
                ('gpsc_id', models.CharField(max_length=100, verbose_name='รหัสพัสดุตาม กพร.')),
                ('keyword', models.TextField(verbose_name='คำค้นหา')),
            ],
            options={
                'verbose_name': 'บันทึกรายการพัสดุ',
                'verbose_name_plural': 'บันทึกรายการพัสดุทั้งหมด',
            },
        ),
    ]
