# Generated by Django 5.2.8 on 2025-11-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='class_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสคลังสินค้า'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='des_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสรายละเอียดพัสดุ'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='des_name',
            field=models.TextField(blank=True, null=True, verbose_name='ชื่อรายละเอียดพัสดุ'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='gpsc_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสพัสดุตาม กพร.'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='keyword',
            field=models.TextField(blank=True, null=True, verbose_name='คำค้นหา'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='type_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสประเภทพัสดุ'),
        ),
    ]
