# Generated by Django 5.2.8 on 2025-11-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryrecord_class_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryRecord',
        ),
    ]
