# Generated by Django 5.2.8 on 2025-12-02 06:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_description_delete_inventoryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='', max_length=50, verbose_name='หน่วยนับ')),
                ('storage_location', models.CharField(max_length=255, verbose_name='ที่เก็บ')),
                ('order_criteria_day', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='เกณฑ์สั่ง (วัน)')),
                ('order_criteria_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='เกณฑ์สั่ง (จำนวน)')),
                ('additional_order_point_day', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='จุดสั่งเพิ่มเติม (วัน)')),
                ('additional_order_point_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='จุดสั่งเพิ่มเติม (จำนวน)')),
                ('safety_criteria_day', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='เกณฑ์ปลอดภัย (วัน)')),
                ('safety_criteria_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='เกณฑ์ปลอดภัย (จำนวน)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='master.description', verbose_name='รายละเอียดพัสดุ')),
            ],
            options={
                'verbose_name': 'พัสดุ',
                'verbose_name_plural': 'พัสดุทั้งหมด',
                'db_table': 'item',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receive', 'ค้างรับ'), ('issue', 'ค้างจ่าย')], max_length=10, verbose_name='ประเภท')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('document_no', models.CharField(max_length=100, verbose_name='หลักฐาน')),
                ('unit', models.CharField(max_length=50, verbose_name='หน่วย')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='จำนวน')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='จัดการแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='document_control.item', verbose_name='พัสดุ')),
            ],
            options={
                'verbose_name': 'รายการค้าง',
                'verbose_name_plural': 'รายการค้างทั้งหมด',
                'db_table': 'pending_transaction',
                'ordering': ['-date', 'item'],
            },
        ),
        migrations.CreateModel(
            name='RelatedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='ชื่อครุภัณฑ์')),
                ('equipment_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสครุภัณฑ์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_equipments', to='document_control.item', verbose_name='พัสดุ')),
            ],
            options={
                'verbose_name': 'ครุภัณฑ์ที่เกี่ยวข้อง',
                'verbose_name_plural': 'ครุภัณฑ์ที่เกี่ยวข้องทั้งหมด',
                'db_table': 'related_equipment',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('receive_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='รับ')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ราคาต่อหน่วย')),
                ('receive_document_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='หลักฐานรับ')),
                ('initial_demand', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ความต้องการขั้นต้น')),
                ('replacement_demand', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ความต้องการทดแทน')),
                ('issue_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='จ่าย')),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='รวมยืม')),
                ('stock_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='คงคลัง')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='ลายมือชื่อ/ผู้รับผิดชอบ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้บันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='document_control.item', verbose_name='พัสดุ')),
            ],
            options={
                'verbose_name': 'รายการรับ-จ่าย',
                'verbose_name_plural': 'รายการรับ-จ่ายทั้งหมด',
                'db_table': 'stock_transaction',
                'ordering': ['-date', 'item'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('alternative_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_for', to='document_control.item', verbose_name='พัสดุแทน')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='document_control.item', verbose_name='พัสดุหลัก')),
            ],
            options={
                'verbose_name': 'พัสดุแทนกันได้',
                'verbose_name_plural': 'พัสดุแทนกันได้ทั้งหมด',
                'db_table': 'alternative_item',
                'unique_together': {('item', 'alternative_item')},
            },
        ),
    ]
