# Generated by Django 5.2.8 on 2025-12-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pending_received_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับค้าง 1'),
        ),
        migrations.AddField(
            model_name='item',
            name='pending_received_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับค้าง 2'),
        ),
        migrations.AddField(
            model_name='item',
            name='pending_received_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับค้าง 3'),
        ),
        migrations.AddField(
            model_name='item',
            name='pending_received_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับค้าง 4'),
        ),
    ]
