# Generated by Django 5.2.8 on 2025-12-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('registration_date', models.DateField()),
                ('document_type', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('first_item', models.CharField(max_length=255)),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('file_storage_date', models.DateField()),
                ('related_document_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
