# Generated by Django 5.2.8 on 2025-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_date', models.DateField()),
                ('pending_evidence', models.CharField(max_length=100)),
                ('pending_unit', models.CharField(max_length=50)),
                ('pending_quantity', models.PositiveIntegerField()),
                ('pending_receive', models.PositiveIntegerField()),
                ('pending_balance', models.PositiveIntegerField()),
                ('pending_signature', models.CharField(max_length=255)),
                ('request_date', models.DateField()),
                ('received_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_evidence', models.CharField(max_length=100)),
                ('request_detail', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('INITIAL', 'ขั้นต้น'), ('REPLACEMENT', 'ทดแทน')], max_length=20)),
                ('issue_quantity', models.PositiveIntegerField()),
                ('total_borrowed', models.PositiveIntegerField()),
                ('stock_balance', models.PositiveIntegerField()),
                ('request_signature', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ทะเบียนคุมวัสดุ',
                'verbose_name_plural': 'ทะเบียนคุมวัสดุทั้งหมด',
            },
        ),
        migrations.AlterModelOptions(
            name='documentrecord',
            options={'verbose_name': 'ทะเบียนเอกสาร', 'verbose_name_plural': 'ทะเบียนเอกสารทั้งหมด'},
        ),
    ]
