# Generated by Django 5.2.8 on 2025-12-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_inventory_alter_documentrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='document_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='documents.documentrecord'),
        ),
    ]
