# Generated by Django 5.2.8 on 2025-12-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_inventory_document_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='pending_balance',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='pending_receive',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='request_detail',
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='days_to_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='inventory_alternate_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='quantity_to_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='related_equipment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='reorder_point_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='reorder_point_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='safety_stock_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='safety_stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_balance1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_balance2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_balance3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_balance4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_receive1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_receive2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_receive3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pending_receive4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pending_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
