# Generated by Django 5.2.8 on 2025-12-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_inventory_pending_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='registerNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
