# Generated by Django 5.2.8 on 2025-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentrecord_registerno'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='previous_stock_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
