# Generated by Django 5.2.8 on 2025-12-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_inventory_issue_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='requester_set_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
