# Generated by Django 5.2.8 on 2025-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentrecord_requester_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrecord',
            name='registration_number',
            field=models.CharField(max_length=100),
        ),
    ]
