# Generated by Django 5.2.8 on 2025-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_documentrecord_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrecord',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
