# Generated by Django 5.2.8 on 2026-01-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_documentrecord_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrecord',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
