# Generated by Django 5.2.8 on 2026-01-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_documentrecord_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='document_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='documents.documentrecord'),
        ),
    ]
