# Generated by Django 5.2.8 on 2026-01-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_inventory_document_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'รับเข้า'), ('ISSUE', 'จ่ายออก')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('evidence', models.CharField(blank=True, default='', max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_borrowed', models.PositiveIntegerField(blank=True, default=0)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='documents.inventory')),
            ],
            options={
                'verbose_name': 'รายการรับ-จ่ายวัสดุ',
                'verbose_name_plural': 'รายการรับ-จ่ายวัสดุทั้งหมด',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
    ]
