version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: kurupun-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pasadu2025
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./pasadu2025.sql:/docker-entrypoint-initdb.d/pasadu2025.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kurupun-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  pgdata:
