version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: kurupun-db
    restart: always
    environment:
      POSTGRES_USER: kurupun
      POSTGRES_PASSWORD: kurupun
      POSTGRES_DB: kurupun
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - kurupun-networks

volumes:
  postgres_data:

networks:
  kurupun-networks:
    driver: bridge
    name: kurupun-networks