# Generated by Django 5.2.8 on 2025-11-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gpscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsc_id', models.CharField(blank=True, max_length=100)),
                ('gpsc_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(blank=True, max_length=100)),
                ('class_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype_id', models.CharField(blank=True, max_length=100)),
                ('ptype_name', models.TextField(blank=True, null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.pclass')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสรายละเอียดพัสดุ')),
                ('des_name', models.TextField(blank=True, null=True, verbose_name='ชื่อรายละเอียดพัสดุ')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='คำค้นหา')),
                ('gpsc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.gpscode')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.pclass')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ptype')),
            ],
            options={
                'verbose_name': 'บันทึกรายการพัสดุ',
                'verbose_name_plural': 'บันทึกรายการพัสดุทั้งหมด',
            },
        ),
    ]
