# Generated by Django 5.2.8 on 2025-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(blank=True, max_length=100)),
                ('dept_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงานทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='invoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invioc_type', models.CharField(blank=True, max_length=100)),
                ('invtype_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ประเภทใบสั่งซื้อ',
                'verbose_name_plural': 'ประเภทใบสั่งซื้อทั้งหมด',
            },
        ),
        migrations.AlterModelOptions(
            name='gpscode',
            options={'verbose_name': 'รหัสพัสดุตาม กพร.', 'verbose_name_plural': 'รหัสพัสดุตาม กพร. ทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='pclass',
            options={'verbose_name': 'หมวดพัสดุ', 'verbose_name_plural': 'หมวดพัสดุทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='ptype',
            options={'verbose_name': 'ประเภทพัสดุ', 'verbose_name_plural': 'ประเภทพัสดุทั้งหมด'},
        ),
    ]
