# Generated by Django 5.2.8 on 2025-11-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_dept_invoicetype_alter_gpscode_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetype',
            old_name='invtype_name',
            new_name='invioc_name',
        ),
    ]
