# Generated by Django 5.2.8 on 2025-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_rename_invtype_name_invoicetype_invioc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสรายการพัสดุ'),
        ),
    ]
