# Generated by Django 5.2.8 on 2025-12-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_inventoryrecord_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Des_id', models.CharField(max_length=100, verbose_name='รหัสรายละเอียด')),
                ('Des_name', models.TextField(blank=True, null=True, verbose_name='ชื่อรายละเอียด')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='คำค้นหา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='master.pclass', verbose_name='หมวดพัสดุ')),
                ('gpsc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='master.gpscode', verbose_name='รหัสพัสดุตาม กพร.')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='master.ptype', verbose_name='ประเภทพัสดุ')),
            ],
            options={
                'verbose_name': 'รายละเอียดพัสดุ',
                'verbose_name_plural': 'รายละเอียดพัสดุทั้งหมด',
                'db_table': 'description',
                'ordering': ['class_id', 'type_id', 'Des_id'],
                'unique_together': {('class_id', 'type_id', 'Des_id')},
            },
        ),
        migrations.DeleteModel(
            name='InventoryRecord',
        ),
    ]
