# Generated by Django 5.2.8 on 2025-12-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_description_delete_inventoryrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='description',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='description',
            name='Des_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัสรายละเอียด'),
        ),
        migrations.AlterField(
            model_name='description',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='master.pclass', verbose_name='หมวดพัสดุ'),
        ),
        migrations.AlterField(
            model_name='description',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='master.ptype', verbose_name='ประเภทพัสดุ'),
        ),
    ]
