# Generated by Django 5.2.8 on 2025-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_description_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='docType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'ประเภทเอกสาร',
                'verbose_name_plural': 'ประเภทเอกสารทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ผู้ส่ง',
                'verbose_name_plural': 'ผู้ส่งทั้งหมด',
            },
        ),
    ]
