# Generated by Django 5.2.8 on 2025-12-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_doctype_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='docType',
        ),
        migrations.DeleteModel(
            name='sender',
        ),
    ]
