# Generated by Django 5.2.8 on 2026-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_delete_doctype_delete_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='item_id',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='รหัสพัสดุ'),
        ),
    ]
