# Generated by Django 5.2.8 on 2026-01-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_description_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='item_id',
        ),
    ]
