# Generated by Django 5.2.8 on 2025-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_number', models.CharField(max_length=255, verbose_name='ทะเบียนที่')),
                ('registration_date', models.DateField(verbose_name='วันที่ลงทะเบียน')),
                ('document_title', models.CharField(max_length=255, verbose_name='เอกสาร')),
                ('sender', models.CharField(max_length=255, verbose_name='จาก')),
                ('first_item', models.CharField(max_length=255, verbose_name='รายการแรกในเอกสาร')),
                ('storage_date', models.DateField(verbose_name='วันที่เก็บเข้าแฟ้ม')),
                ('related_document_number', models.CharField(max_length=255, verbose_name='เลขที่เอกสารที่เกี่ยวข้อง')),
                ('withdrawal_set_number', models.CharField(max_length=255, verbose_name='เลขที่ชุดเบิก')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'Document Registry',
                'verbose_name_plural': 'Document Registries',
                'ordering': ['-registration_date'],
            },
        ),
    ]
