# Generated by Django 5.2.8 on 2025-11-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentRegistry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentregistry',
            options={'ordering': ['-registration_date'], 'verbose_name': 'ทะเบียนเอกสาร', 'verbose_name_plural': 'ทะเบียนเอกสารทั้งหมด'},
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_criteria', models.CharField(blank=True, max_length=255, null=True)),
                ('reorder_point', models.CharField(blank=True, max_length=255, null=True)),
                ('safety_stock', models.CharField(blank=True, max_length=255, null=True)),
                ('related_equipment', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('doc_date_left', models.DateField(blank=True, null=True)),
                ('evidence_left', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_left', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_left', models.IntegerField(blank=True, null=True)),
                ('pending_receive_1', models.IntegerField(blank=True, null=True)),
                ('pending_receive_2', models.IntegerField(blank=True, null=True)),
                ('pending_receive_3', models.IntegerField(blank=True, null=True)),
                ('pending_receive_4', models.IntegerField(blank=True, null=True)),
                ('doc_date_right', models.DateField(blank=True, null=True)),
                ('received_qty', models.IntegerField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_right', models.CharField(blank=True, max_length=255, null=True)),
                ('demand_initial', models.IntegerField(blank=True, null=True)),
                ('demand_replace', models.IntegerField(blank=True, null=True)),
                ('issued_qty', models.IntegerField(blank=True, null=True)),
                ('total_borrowed', models.IntegerField(blank=True, null=True)),
                ('stock_balance', models.IntegerField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='documentRegistry.documentregistry', verbose_name='ทะเบียนเอกสาร')),
            ],
            options={
                'verbose_name': 'บันทึกรายการพัสดุ',
                'verbose_name_plural': 'บันทึกรายการพัสดุทั้งหมด',
            },
        ),
    ]
