version: '3.8'

services:
  backend:
    build: .
    container_name: kurupun-service
    image: python:3.12-slim
    command: bash -c "
      cp .env.dev .env &&
      python manage.py migrate &&
      echo 'from django.contrib.auth import get_user_model; User = get_user_model();
      User.objects.filter(username=\"admin\").exists() or
      User.objects.create_superuser(\"admin\", \"admin@mail.com\", \"112233Pass\")' | python manage.py shell &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - kurupun-networks

networks:
  kurupun-networks:
    driver: bridge
    name: kurupun-networks