version: '3.8'

services:
  web:
    build: .
    container_name: kurupun-web
    command: bash -c "cp .env.dev .env && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - kurupun-networks

networks:
  kurupun-networks:
    driver: bridge
    name: kurupun-networks